name: design_system_qclass
description: "Pacote com os componentes utilizados no QClass"
version: 0.0.1
homepage:
publish_to: "none"


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shimmer: ^3.0.0  
  flutter_svg: ^2.0.10+1
  brasil_fields: ^1.14.0
  cached_network_image: ^3.3.1
  mask_text_input_formatter: ^2.5.0
  currency_text_input_formatter: ^2.1.10


  # core:
  #   path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
