name: example_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  design_system_qclass:
    path: ../

  #====== livro de widgets ======
  widgetbook: ^3.8.0  
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  #======= livro de widget ======
  widgetbook_generator: ^3.7.0


flutter:
  uses-material-design: true
